# Generated by Django 3.2.8 on 2021-12-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0002_delete_upcoming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Up_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=80)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='card')),
                ('heading_tag', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
