# Generated by Django 3.2.8 on 2022-01-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0010_auto_20211206_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.IntegerField(max_length=30)),
                ('website', models.URLField()),
                ('hosting', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
    ]
