# Generated by Django 3.2.8 on 2022-01-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0011_employeeform'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=20)),
            ],
        ),
    ]
