# Generated by Django 3.2.8 on 2021-12-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upcoming',
        ),
    ]
