# Generated by Django 3.2.8 on 2021-12-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0003_up_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='up_events',
            name='heading',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
