# Generated by Django 3.2.8 on 2021-12-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0006_auto_20211203_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='image',
            field=models.ImageField(default=1, upload_to='cover'),
            preserve_default=False,
        ),
    ]
