# Generated by Django 3.2.8 on 2021-12-05 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0009_auto_20211203_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='metting_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=300)),
                ('descriptions', models.TextField(max_length=2000)),
                ('hours', models.CharField(max_length=400)),
                ('booking_number', models.CharField(blank=True, max_length=30)),
                ('facebook', models.URLField(max_length=100)),
                ('twitter', models.URLField(max_length=100)),
                ('linkedin', models.URLField(max_length=100)),
                ('behance', models.URLField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='up_events',
            name='heading_tag',
        ),
        migrations.AddField(
            model_name='up_events',
            name='title',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.AddField(
            model_name='metting_details',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_app.up_events'),
        ),
    ]
